### PR TITLE
add: edgebendediting ignores edges with class "edgebendediting-ignore"

### PR DESCRIPTION
**Pull request by Flui**
this gives you the ability to decide which edges are editable

### CODE REVIEW

**Comment by ugurdogrusoz** [comment]
@metincansiper how much do you think this would this affect performance?

**Comment by metincansiper** [comment]
@ugurdogrusoz  I think that this will not affect the performance that much. 

@Flui one line in your commits seems problematic to me (https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/pull/10/files#diff-08983fd48b4b0170bc45d1c2641df9d2R12). I think that you make the same check in the following way (https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/pull/10/files#diff-fd4151316527472125b2d071c6d55059R12) and it should be done here similarly. Am I wright?

@Flui I think that in the following line  (https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/pull/10/files#diff-08983fd48b4b0170bc45d1c2641df9d2R12) you want to disable changing bend points upon undo/redo as well? (Though it may not work successfully because of the reason I mentioned above) Is this true? @ugurdogrusoz do you think that changing bend points should be disabled upon undo/redo as well?

**Comment by Flui** [comment]
Oh you are right that does not make sense at all to disable it on undo/redo and I dont think that this has a huge impact in Performance.

**Comment by metincansiper** [comment]
@Flui Thanks a lot for your contribution. I merged this PR.

**Pull request merged**
